# Generated by Django 5.1.3 on 2025-08-30 07:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_token",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
