# Generated by Django 5.1.3 on 2025-08-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0002_user_activation_token_user_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("size", models.CharField(max_length=200)),
                ("boxes", models.IntegerField()),
                ("extra_units", models.IntegerField()),
                ("unit_per_box", models.IntegerField()),
                ("per_liter_value", models.FloatField()),
                ("total_ml_in", models.IntegerField()),
                ("total_value_in", models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(default="Basic", max_length=200),
            preserve_default=False,
        ),
    ]
