# Generated by Django 5.2.4 on 2025-09-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_products_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='boxes',
        ),
        migrations.RemoveField(
            model_name='products',
            name='extra_units',
        ),
        migrations.RemoveField(
            model_name='products',
            name='total_ml_in',
        ),
        migrations.RemoveField(
            model_name='products',
            name='total_value_in',
        ),
        migrations.AddField(
            model_name='products',
            name='branded',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.IntegerField(),
        ),
    ]
