# Generated by Django 5.2.4 on 2025-09-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_remove_products_boxes_remove_products_extra_units_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('boxes', models.IntegerField()),
                ('extra_units', models.IntegerField()),
                ('unit_per_box', models.IntegerField()),
                ('per_liter_value', models.FloatField()),
                ('total_ml_in', models.IntegerField()),
                ('total_value_in', models.FloatField()),
            ],
        ),
    ]
