# Generated by Django 5.2.4 on 2025-09-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
