# Generated by Django 5.2.4 on 2025-09-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_inventory_approved_products_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='branded',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
