# Generated by Django 5.1.3 on 2025-09-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_app", "0007_inventory_branded"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pending_inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("size", models.CharField(max_length=200)),
                ("branded", models.BooleanField()),
                ("boxes", models.IntegerField()),
                ("extra_units", models.IntegerField()),
                ("unit_per_box", models.IntegerField()),
                ("per_liter_value", models.FloatField()),
                ("total_ml_in", models.IntegerField()),
                ("total_value_in", models.FloatField()),
                ("approved", models.BooleanField(default=False)),
                ("total_units", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="approved",
        ),
        migrations.AddField(
            model_name="inventory",
            name="total_units",
            field=models.IntegerField(default=0),
        ),
    ]
