# Generated by Django 5.2 on 2025-09-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend_app", "0009_invoice_invoiceitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pending_inventory",
            name="size",
            field=models.IntegerField(),
        ),
    ]
